-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    - id: black
      language_version: python3

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    - id: trailing-whitespace
      exclude: ^channelstream/static/|^demo/chat/static/
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-symlinks
    - id: end-of-file-fixer
      exclude: ^channelstream/static/|^demo/chat/static/
    - id: debug-statements
      language_version: python3
    - id: requirements-txt-fixer
